export const styles = {
  page: {
    minHeight: "100vh",
    background: "var(--bg-screen)",
    color: "var(--text-primary)",
    fontFamily: "'Manrope', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    padding: "0 0 40px 0",
    position: "relative",
  },
  pageAuth: {
    minHeight: "100vh",
    background: "var(--bg-screen)",
    color: "var(--text-primary)",
    fontFamily: "'Manrope', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    padding: "0 0 40px 0",
    position: "relative",
    overflow: "hidden",
  },
  gateCard: { position: "relative", zIndex: 1, maxWidth: 380, margin: "80px auto", background: "rgba(25,28,33,0.88)", backdropFilter: "blur(6px)", borderRadius: 14, padding: "32px 28px", textAlign: "center", boxShadow: "0 20px 60px rgba(0,0,0,0.5)", border: "1px solid var(--border-subtle)" },
  logoBadgeLarge: {
    position: "relative", width: 64, height: 64, borderRadius: 18,
    background: "#FFB43A",
    display: "flex", alignItems: "center", justifyContent: "center",
    margin: "0 auto 16px",
  },
  logoBeaconLarge: {
    position: "absolute", top: -4, right: -4, width: 16, height: 16, borderRadius: "50%",
    background: "#3BD07A", border: "3px solid var(--bg-screen)",
  },
  logoBadge: {
    position: "relative", width: 38, height: 38, borderRadius: 12,
    background: "#FFB43A",
    display: "flex", alignItems: "center", justifyContent: "center",
    flexShrink: 0,
  },
  gateTitle: { fontFamily: "'Manrope', sans-serif", fontSize: 30, letterSpacing: 0.5, fontWeight: 700, margin: 0 },
  gateSub: { color: "var(--text-muted)", fontSize: 14, marginTop: 10, lineHeight: 1.5 },
  header: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "16px 24px", borderBottom: "1px solid var(--border-subtle)", position: "sticky", top: 0, background: "var(--bg-bar)", zIndex: 10, flexWrap: "nowrap", gap: 10 },
  title: { fontFamily: "'Manrope', sans-serif", fontSize: 18, letterSpacing: "-0.01em", fontWeight: 800, margin: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  headerSubtitle: { fontSize: 12, fontWeight: 500, color: "var(--text-muted)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", display: "block" },
  statusPill: {
    display: "flex", alignItems: "center", gap: 7, padding: "7px 12px", borderRadius: 999,
    border: "1px solid", fontSize: 12, fontWeight: 700, cursor: "pointer", fontFamily: "'Manrope', sans-serif",
  },
  statusPillOn: { background: "rgba(59,208,122,0.10)", borderColor: "rgba(59,208,122,0.28)", color: "var(--positive-text)" },
  statusPillOff: { background: "var(--surface-tile)", borderColor: "var(--border-strong)", color: "var(--text-muted)" },
  onlineDriversBadge: {
    display: "flex", alignItems: "center", gap: 5, padding: "6px 10px", borderRadius: 999,
    border: "1px solid rgba(255,180,58,0.28)", background: "rgba(255,180,58,0.10)", color: "var(--accent-text)",
    fontSize: 12, fontWeight: 700, fontFamily: "'Manrope', sans-serif",
  },
  dateFilterRow: { display: "flex", alignItems: "center", gap: 6, flexWrap: "wrap" },
  iconBtn: { background: "var(--border-subtle)", border: "1px solid var(--border-outline)", color: "var(--text-primary)", borderRadius: 8, padding: "8px 10px", cursor: "pointer", display: "flex", alignItems: "center", fontSize: 12 },
  iconCircleBtn: {
    position: "relative", width: 38, height: 38, borderRadius: "50%",
    background: "var(--surface-card)", border: "1px solid var(--border-outline)", color: "var(--text-tertiary)",
    display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", flexShrink: 0,
  },
  iconCircleBtnActive: { borderColor: "#FFB43A", color: "var(--accent-text)", background: "rgba(255,180,58,0.10)" },
  iconCircleDot: {
    position: "absolute", top: 2, right: 2, width: 8, height: 8, borderRadius: "50%",
    background: "#FFB43A", border: "2px solid var(--bg-bar)",
  },
  tabs: { display: "flex", gap: 8, padding: "16px 24px", alignItems: "center", flexWrap: "wrap" },
  tab: { background: "transparent", border: "1px solid var(--border-outline)", color: "var(--text-muted)", padding: "8px 14px", borderRadius: 20, cursor: "pointer", fontSize: 13 },
  tabActive: { background: "#FFB43A", color: "#1A1206", borderColor: "#FFB43A", fontWeight: 600 },
  btnPrimary: { background: "#FFB43A", color: "#1A1206", border: "none", padding: "12px 18px", borderRadius: 10, fontWeight: 700, cursor: "pointer", display: "flex", alignItems: "center", fontSize: 15, minHeight: 48 },
  btnGhost: { background: "transparent", border: "1px solid var(--border-outline)", color: "var(--text-primary)", padding: "11px 16px", borderRadius: 10, cursor: "pointer", fontSize: 14.5, fontWeight: 600, minHeight: 46 },
  btnClaim: { background: "#FFB43A", color: "#1A1206", border: "none", padding: "12px 20px", borderRadius: 12, fontWeight: 800, cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 16, minHeight: 52 },
  formCard: {
    margin: "0 24px 20px", background: "var(--surface-accent)", border: "1px solid rgba(255,180,58,0.35)",
    borderRadius: 14, padding: 18, display: "flex", flexDirection: "column", gap: 14,
  },
  wizardOverlay: {
    position: "fixed", inset: 0, background: "var(--bg-screen)", zIndex: 200,
    display: "flex", flexDirection: "column",
  },
  wizardForm: { display: "flex", flexDirection: "column", height: "100%", minHeight: 0 },
  wizardHeader: {
    display: "flex", alignItems: "center", gap: 12, padding: "14px 16px",
    borderBottom: "1px solid var(--border-subtle)", flexShrink: 0,
  },
  wizardNavBtn: {
    background: "var(--surface-card)", border: "1px solid var(--border-subtle)", color: "var(--text-primary)",
    borderRadius: 10, width: 38, height: 38, display: "flex", alignItems: "center",
    justifyContent: "center", cursor: "pointer", flexShrink: 0,
  },
  wizardStepLabel: {
    fontFamily: "'IBM Plex Mono', monospace", fontSize: 11, fontWeight: 800,
    color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: "0.10em", marginBottom: 6,
  },
  wizardStepDots: { display: "flex", gap: 6 },
  wizardStepDot: { height: 4, borderRadius: 2, flex: 1, background: "var(--border-subtle)" },
  wizardStepDotActive: { background: "#FFB43A" },
  wizardBody: { flex: 1, minHeight: 0, overflowY: "auto", overscrollBehaviorY: "contain", padding: "20px 20px 28px" },
  wizardTitle: { fontSize: 21, fontWeight: 800, margin: "0 0 4px", fontFamily: "'Manrope', sans-serif", letterSpacing: "-0.01em" },
  wizardSubtitle: { fontSize: 13, color: "var(--text-muted)", margin: "0 0 22px" },
  wizardSectionTitle: {
    fontFamily: "'Manrope', sans-serif", fontSize: 13, fontWeight: 700,
    color: "var(--text-primary)", margin: "0 0 12px",
  },
  wizardModeBtn: {
    display: "flex", alignItems: "center", width: "100%", textAlign: "left",
    background: "var(--surface-card)", border: "1.5px solid var(--border-subtle)", color: "var(--text-tertiary)",
    padding: "14px 16px", borderRadius: 12, cursor: "pointer", fontSize: 15, fontWeight: 700,
    minHeight: 52,
  },
  wizardModeBtnActive: { borderColor: "#FFB43A", background: "rgba(255,180,58,0.12)", color: "var(--text-primary)" },
  wizardSummaryCard: { background: "var(--surface-card)", border: "1px solid var(--border-subtle)", borderRadius: 16, padding: 16 },
  wizardFooter: {
    display: "flex", gap: 10, padding: "14px 16px", borderTop: "1px solid var(--border-subtle)",
    background: "var(--bg-screen)", flexShrink: 0,
  },
  fullPageHeader: {
    display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12,
    padding: "16px 16px", borderBottom: "1px solid var(--border-subtle)", flexShrink: 0,
  },
  fullPageTitle: { fontSize: 17.5, fontWeight: 800, margin: 0, fontFamily: "'Manrope', sans-serif", flex: 1, textAlign: "center" },
  myCoursesSectionTitle: {
    display: "flex", alignItems: "center", gap: 8, fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 11.5, fontWeight: 800, color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: "0.10em",
    margin: "0 0 12px",
  },
  formRow: { display: "flex", gap: 8, flexWrap: "wrap" },
  formGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 12 },
  typeChip: { border: "none", padding: "12px 16px", borderRadius: 12, cursor: "pointer", fontSize: 14.5, fontWeight: 700, minHeight: 48 },
  input: { background: "var(--surface-card)", border: "1.5px solid var(--border-subtle)", color: "var(--text-primary)", padding: "14px 14px", borderRadius: 10, fontSize: 16.5, outline: "none", minHeight: 50 },
  checkboxRow: { display: "flex", alignItems: "center", gap: 10, fontSize: 14.5, color: "var(--text-tertiary)" },
  fieldLabel: { display: "flex", flexDirection: "column", gap: 7, fontSize: 13.5, color: "var(--text-secondary)", fontWeight: 700 },
  formLabel: {
    display: "flex", flexDirection: "column", gap: 7,
    fontFamily: "'IBM Plex Mono', monospace", fontSize: 11, fontWeight: 800,
    color: "var(--text-tertiary)", textTransform: "uppercase", letterSpacing: "0.10em",
  },
  sectionLabel: {
    fontFamily: "'Manrope', sans-serif", fontSize: 11.5, fontWeight: 700,
    color: "var(--text-faint)", textTransform: "uppercase", letterSpacing: 0.6,
    marginTop: 18, marginBottom: 2,
  },
  sectionDivider: { height: 1, background: "var(--border-subtle)", margin: "18px 0 0" },
  categoryBtn: {
    display: "flex", alignItems: "center", justifyContent: "space-between", width: "100%",
    background: "var(--bg-screen)", border: "1.5px solid var(--border-subtle)", borderRadius: 12,
    padding: "16px 16px", minHeight: 56, fontSize: 15.5, fontWeight: 700, color: "var(--text-primary)",
    cursor: "pointer", textAlign: "left",
  },
  categoryBtnLeft: { display: "flex", alignItems: "center", gap: 12 },
  togglePill: {
    display: "flex", alignItems: "center", justifyContent: "center", gap: 8,
    border: "1.5px solid var(--border-outline)", background: "transparent", color: "var(--text-tertiary)",
    padding: "13px 16px", borderRadius: 12, cursor: "pointer", fontSize: 14.5, fontWeight: 600,
    minHeight: 50, flex: 1,
  },
  collapsibleHeader: {
    display: "flex", alignItems: "center", justifyContent: "space-between",
    background: "transparent", border: "none", color: "var(--text-muted)", cursor: "pointer",
    fontSize: 14, fontWeight: 600, padding: "6px 2px", width: "100%",
  },
  swapBtn: {
    position: "absolute", right: -6, top: "50%", transform: "translateY(-50%)", zIndex: 5,
    background: "#FFB43A", color: "#1A1206", border: "3px solid var(--surface-card)", borderRadius: "50%",
    width: 34, height: 34, cursor: "pointer", fontSize: 14, fontWeight: 700,
    display: "flex", alignItems: "center", justifyContent: "center",
  },
  routeCard: { position: "relative", background: "var(--surface-card)", border: "1px solid var(--border-subtle)", borderRadius: 14, marginTop: 7 },
  routeRowInput: {
    border: "none", background: "transparent", outline: "none", color: "var(--text-primary)",
    fontSize: 15, fontWeight: 600, fontFamily: "'Manrope', sans-serif", padding: 0, flex: 1, minWidth: 0,
  },
  tpmrBadge: {
    fontSize: 12, fontWeight: 700, color: "#1A1206", background: "var(--text-muted)",
    padding: "2px 6px", borderRadius: 4, marginRight: 4,
  },
  suggestionBox: {
    position: "absolute",
    top: "100%",
    left: 0,
    right: 0,
    background: "var(--surface-card)",
    border: "1.5px solid var(--border-outline)",
    borderRadius: 10,
    marginTop: 6,
    maxHeight: 260,
    overflowY: "auto",
    zIndex: 50,
    boxShadow: "0 10px 30px rgba(0,0,0,0.5)",
  },
  suggestionItem: {
    display: "flex",
    alignItems: "center",
    padding: "14px 14px",
    fontSize: 15,
    color: "var(--text-primary)",
    cursor: "pointer",
    borderBottom: "1px solid var(--border-subtle)",
    minHeight: 48,
  },
  photoPreview: { maxWidth: 160, maxHeight: 160, borderRadius: 8, display: "block", border: "1px solid var(--border-outline)" },
  photoRemoveBtn: {
    position: "absolute", top: -8, right: -8, background: "#E5484D", color: "#fff",
    border: "none", borderRadius: "50%", width: 24, height: 24, display: "flex",
    alignItems: "center", justifyContent: "center", cursor: "pointer",
  },
  cardThumb: { width: "100%", maxHeight: 140, objectFit: "cover", borderRadius: 8, marginBottom: 10, display: "block" },
  modalPhoto: { width: "100%", borderRadius: 10, marginTop: 12, display: "block" },
  board: { padding: "0 24px", display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))", gap: 14 },
  mapContainer: { width: "100%", height: "45vh", minHeight: 320, maxHeight: 460, borderRadius: 12, border: "1px solid var(--border-strong)", overflow: "hidden", position: "relative", zIndex: 1, touchAction: "none" },
  empty: { color: "var(--text-faint)", padding: "40px 0", textAlign: "center" },
  emptyState: { padding: "50px 24px", textAlign: "center", maxWidth: 380, margin: "0 auto" },
  emptyIcon: {
    width: 72, height: 72, borderRadius: "50%", background: "var(--border-subtle)",
    display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 16px",
    border: "1px solid var(--border-strong)",
  },
  emptyTitle: { color: "var(--text-primary)", fontSize: 16, fontWeight: 600, margin: "0 0 8px" },
  emptySub: { color: "var(--text-faint)", fontSize: 13, lineHeight: 1.5, margin: 0 },
  card: { background: "var(--surface-card)", borderRadius: 18, padding: "15px 16px", position: "relative", border: "1px solid var(--border-subtle)" },
  urgentBadge: { position: "absolute", top: -8, right: 12, background: "#E5484D", color: "#fff", fontSize: 13, fontWeight: 700, padding: "3px 8px", borderRadius: 6, display: "flex", alignItems: "center" },
  cardHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 10 },
  typeTag: { filter: "var(--tag-filter)", fontFamily: "'IBM Plex Mono', monospace", fontSize: 12, fontWeight: 700, padding: "4px 8px", borderRadius: 6, display: "flex", alignItems: "center", letterSpacing: "0.10em", textTransform: "uppercase" },
  statusTag: { filter: "var(--tag-filter)", fontSize: 13.5, fontWeight: 800, padding: "5px 10px", borderRadius: 999, whiteSpace: "nowrap" },
  metaRow: { display: "flex", gap: 14, fontSize: 14, color: "var(--text-muted-strong)", marginBottom: 8, flexWrap: "wrap" },
  metaItem: { display: "flex", alignItems: "center", gap: 4 },
  tarifTag: {
    display: "flex", alignItems: "center", fontSize: 20, fontWeight: 800,
    fontFamily: "'Manrope', sans-serif", letterSpacing: "-0.02em",
    fontVariantNumeric: "tabular-nums", color: "var(--text-primary)",
  },
  contactBtn: {
    flex: 1, textAlign: "center", background: "var(--border-subtle)", border: "1px solid var(--border-outline)",
    color: "var(--text-primary)", padding: "9px 12px", borderRadius: 8, fontSize: 13, fontWeight: 600,
    textDecoration: "none",
  },
  callBtn: {
    display: "flex", alignItems: "center", gap: 12, flex: 1,
    background: "rgba(59,208,122,0.10)", border: "1px solid rgba(59,208,122,0.28)",
    borderRadius: 12, padding: "10px 14px", textDecoration: "none", minWidth: 0,
  },
  callBtnIcon: {
    width: 36, height: 36, borderRadius: "50%", background: "#3BD07A",
    display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0,
  },
  callBtnText: { display: "flex", flexDirection: "column", gap: 1, minWidth: 0 },
  callBtnLabel: { fontSize: 14, fontWeight: 700, color: "var(--text-primary)" },
  callBtnSub: { fontSize: 12, color: "var(--text-muted)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  smsIconBtn: {
    width: 46, height: 46, borderRadius: 12, border: "1px solid var(--border-outline)", background: "transparent",
    display: "flex", alignItems: "center", justifyContent: "center", color: "var(--text-tertiary)", flexShrink: 0,
  },
  btnPrimaryAction: {
    display: "flex", alignItems: "center", justifyContent: "center", gap: 8, width: "100%",
    background: "#FFB43A", color: "#1A1206", border: "none", borderRadius: 12,
    padding: "17px 18px", fontSize: 17, fontWeight: 800, cursor: "pointer", minHeight: 58,
  },
  btnSecondaryAction: {
    display: "flex", alignItems: "center", justifyContent: "center", gap: 8, flex: 1,
    background: "transparent", color: "var(--text-secondary)", border: "1.5px solid var(--border-outline)", borderRadius: 12,
    padding: "14px 16px", fontSize: 14, fontWeight: 700, cursor: "pointer",
  },
  btnUtilityAction: {
    display: "flex", alignItems: "center", justifyContent: "center", gap: 6,
    flex: "1 1 84px", minWidth: 0, whiteSpace: "nowrap",
    background: "var(--surface-card)", color: "var(--text-tertiary)", border: "1px solid var(--border-subtle)", borderRadius: 10,
    padding: "10px 8px", fontSize: 12, fontWeight: 600, cursor: "pointer",
  },
  notes: { fontSize: 14, color: "var(--text-tertiary)", background: "var(--surface-tile)", padding: "10px 12px", borderRadius: 8, marginBottom: 10 },
  priorityBanner: { display: "flex", alignItems: "center", fontSize: 14, fontWeight: 600, color: "var(--accent-text)", background: "rgba(255,180,58,0.1)", border: "1px solid rgba(255,180,58,0.3)", padding: "10px 12px", borderRadius: 8, marginBottom: 10 },
  modifBanner: { fontSize: 14, fontWeight: 700, color: "var(--text-primary)", background: "rgba(255,140,0,0.16)", border: "2px solid #FF8C00", padding: "10px 12px", borderRadius: 8, marginBottom: 10 },
  pendingBanner: { fontSize: 14, fontWeight: 600, color: "var(--accent-text)", background: "rgba(255,180,58,0.1)", border: "1px solid rgba(255,180,58,0.3)", padding: "10px 12px", borderRadius: 8, marginBottom: 10 },
  cardFooter: { display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: 10, borderTop: "1px solid var(--border-strong)", paddingTop: 12 },
  postedBy: { fontSize: 13, color: "var(--text-muted)" },
  expressBox: {
    marginTop: 26, padding: 16, borderRadius: 14,
    background: "rgba(255,180,58,0.07)", border: "1px solid rgba(255,180,58,0.3)",
  },
  hintBanner: { margin: "0 24px 16px", background: "var(--border-subtle)", padding: "10px 14px", borderRadius: 8, fontSize: 13, color: "var(--text-muted)" },
  gainsCard: {
    padding: 18, borderRadius: 20, background: "var(--surface-card)", border: "1px solid var(--border-subtle)",
    display: "flex", justifyContent: "space-between", alignItems: "flex-end", gap: 12,
  },
  gainsLabel: { fontFamily: "'IBM Plex Mono', monospace", fontSize: 11, fontWeight: 600, letterSpacing: "0.12em", color: "var(--text-muted)", textTransform: "uppercase" },
  gainsAmount: { fontSize: 32, fontWeight: 800, letterSpacing: "-0.02em", color: "var(--text-primary)" },
  gainsCount: { fontSize: 13, fontWeight: 600, color: "var(--text-muted)", textAlign: "right", lineHeight: 1.3 },
  errorBanner: { margin: "0 24px 16px", background: "#E5484D", color: "#FFFFFF", padding: "10px 14px", borderRadius: 8, display: "flex", justifyContent: "space-between", fontSize: 13 },
  modalOverlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.6)", display: "flex", alignItems: "center", justifyContent: "center", padding: 20, zIndex: 100 },
  modalCard: { background: "var(--border-subtle)", borderRadius: 14, padding: 24, maxWidth: 440, width: "100%", maxHeight: "85vh", overflowY: "auto", overflowX: "hidden", boxShadow: "0 20px 60px rgba(0,0,0,0.5)" },
  modalHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 },
  modalTitle: { fontSize: 18, margin: "0 0 16px", color: "var(--text-primary)" },
  modalGrid: { display: "flex", flexDirection: "column", gap: 10 },
  navIconBtn: {
    display: "flex", alignItems: "center", justifyContent: "center",
    width: 32, height: 32, borderRadius: "50%", flexShrink: 0,
    color: "#fff", fontSize: 13, fontWeight: 800, textDecoration: "none",
  },
  modalRow: { display: "flex", alignItems: "center", gap: 8, fontSize: 14 },
  modalActions: { display: "flex", gap: 8, flexWrap: "wrap", justifyContent: "flex-end", marginTop: 20, paddingTop: 16, borderTop: "1px solid var(--border-outline)" },
  bottomNav: {
    position: "fixed", bottom: 0, left: 0, right: 0, height: 64,
    background: "var(--bg-bar)", borderTop: "1px solid var(--border-subtle)",
    alignItems: "center", justifyContent: "space-around",
    zIndex: 90, paddingBottom: "env(safe-area-inset-bottom, 0px)",
  },
  bottomNavBtn: {
    background: "none", border: "none", display: "flex", flexDirection: "column",
    alignItems: "center", gap: 3, cursor: "pointer", padding: "6px 10px", minWidth: 56,
  },
  bottomNavLabel: { fontSize: 11, fontWeight: 600 },
  navBadge: {
    position: "absolute", top: 2, right: "28%",
    background: "#E5484D", color: "#fff", fontSize: 10, fontWeight: 800,
    minWidth: 16, height: 16, borderRadius: 8, display: "flex",
    alignItems: "center", justifyContent: "center", padding: "0 3px",
    border: "1.5px solid var(--bg-bar)",
  },
  bottomNavFabSlot: { width: 58, flexShrink: 0 },
  bottomNavFabFloating: {
    position: "fixed", bottom: 34, left: "50%", transform: "translateX(-50%)",
    background: "#FFB43A", border: "3px solid var(--bg-screen)", borderRadius: "50%",
    width: 58, height: 58, alignItems: "center", justifyContent: "center",
    cursor: "pointer", boxShadow: "0 10px 24px rgba(255,180,58,0.28)", zIndex: 91,
  },
  priorityAlertOverlay: {
    position: "fixed", inset: 0, zIndex: 300,
    background: "rgba(10,11,15,0.88)", backdropFilter: "blur(3px)",
    display: "flex", alignItems: "center", justifyContent: "center", padding: 16,
  },
  priorityAlertCard: {
    width: "100%", maxWidth: 420, background: "var(--surface-card)",
    border: "2px solid #FFB43A", borderRadius: 18, padding: 18,
    boxShadow: "0 0 40px rgba(255,180,58,0.35)",
    maxHeight: "88vh", overflowY: "auto",
  },
  priorityAlertTop: {
    display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10,
  },
  priorityAlertPill: {
    background: "#FFB43A", color: "#1A1206", fontWeight: 800,
    fontSize: 12, letterSpacing: "0.04em", padding: "6px 10px", borderRadius: 999,
  },
  priorityAlertSub: {
    color: "var(--text-muted)", fontSize: 13, margin: "10px 0 14px",
  },
  priorityAlertBody: {
    background: "var(--bg-screen)", border: "1px solid var(--border-subtle)",
    borderRadius: 12, padding: 14, marginBottom: 16,
  },
  priorityAlertRoute: {
    display: "flex", flexDirection: "column", gap: 6, fontSize: 15, lineHeight: 1.4,
  },
  priorityAlertMeta: {
    display: "flex", flexWrap: "wrap", gap: 12, marginTop: 12,
    fontSize: 13, color: "var(--text-muted)", alignItems: "center",
  },
  priorityAlertActions: { display: "flex", gap: 10 },
  claimToast: {
    position: "fixed", top: 16, left: 16, right: 16, maxWidth: 420, margin: "0 auto", zIndex: 250,
    background: "var(--surface-card)", border: "1px solid #FFB43A", borderRadius: 14,
    padding: "14px 16px", boxShadow: "0 12px 32px rgba(0,0,0,0.5)",
  },
  claimToastHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10, marginBottom: 8 },
  claimToastTitle: { display: "flex", alignItems: "center", fontSize: 14, color: "var(--text-primary)" },
  claimToastRoute: { fontSize: 13, color: "var(--text-tertiary)", marginBottom: 12 },
  claimToastActions: { display: "flex", gap: 10 },
  claimToastHint: { fontSize: 11, color: "var(--text-faint)", marginTop: 10, textAlign: "center" },
  pullBanner: {
    position: "fixed", top: 0, left: 0, right: 0, zIndex: 200,
    background: "#FFB43A", color: "#1A1206", textAlign: "center",
    padding: "10px 0", fontSize: 13, fontWeight: 700,
  },
};
